// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaGHMM.Models;

#nullable disable

namespace SistemaGHMM.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaGHMM.Models.AvisoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AvisoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvisoConteudo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AvisoConteudo");

                    b.Property<int>("AvisoTipoId")
                        .HasColumnType("int")
                        .HasColumnName("AvisoTipo");

                    b.Property<bool>("AvisoVisto")
                        .HasColumnType("bit")
                        .HasColumnName("AvisoVisto");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("Usuario");

                    b.HasKey("Id");

                    b.HasIndex("AvisoTipoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Aviso");
                });

            modelBuilder.Entity("SistemaGHMM.Models.AvisoTipoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AvisoTipoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvisoTipoNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AvisoTipoNome");

                    b.HasKey("Id");

                    b.ToTable("AvisoTipo");
                });

            modelBuilder.Entity("SistemaGHMM.Models.CargoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CargoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CargoNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CargoNome");

                    b.HasKey("Id");

                    b.ToTable("Cargo");
                });

            modelBuilder.Entity("SistemaGHMM.Models.CategoriaPecaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoriaPecaId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoriaPecaNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CategoriaPecaNome");

                    b.HasKey("Id");

                    b.ToTable("CategoriaPeca");
                });

            modelBuilder.Entity("SistemaGHMM.Models.FabricanteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FabricanteId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FabricanteNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FabricanteNome");

                    b.HasKey("Id");

                    b.ToTable("Fabricante");
                });

            modelBuilder.Entity("SistemaGHMM.Models.FornecedorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FornecedorId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FornecedorCnpj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FornecedorCnpj");

                    b.Property<string>("FornecedorNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FornecedorNome");

                    b.HasKey("Id");

                    b.ToTable("Fornecedor");
                });

            modelBuilder.Entity("SistemaGHMM.Models.ManutencaoEPecasModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ManutencaoEPecasId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ManutencaoId")
                        .HasColumnType("int")
                        .HasColumnName("ManutencaoId");

                    b.Property<int>("PecaId")
                        .HasColumnType("int")
                        .HasColumnName("PecaId");

                    b.HasKey("Id");

                    b.HasIndex("ManutencaoId");

                    b.HasIndex("PecaId");

                    b.ToTable("ManutencaoEPecas");
                });

            modelBuilder.Entity("SistemaGHMM.Models.ManutencaoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ManutencaoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ManutencaoCusto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ManutencaoCusto");

                    b.Property<DateTime>("ManutencaoData")
                        .HasColumnType("datetime2")
                        .HasColumnName("ManutencaoData");

                    b.Property<string>("ManutencaoDescricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ManutencaoDescricao");

                    b.Property<int>("TecnicosId")
                        .HasColumnType("int")
                        .HasColumnName("Tecnicos");

                    b.Property<int>("TipoManutencaoId")
                        .HasColumnType("int")
                        .HasColumnName("TipoManutencaoId");

                    b.HasKey("Id");

                    b.HasIndex("TecnicosId");

                    b.HasIndex("TipoManutencaoId");

                    b.ToTable("Manutencao");
                });

            modelBuilder.Entity("SistemaGHMM.Models.MaquinaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaquinaId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FabricanteId")
                        .HasColumnType("int")
                        .HasColumnName("FabricanteId");

                    b.Property<DateTime>("MaquinaDataAquisicao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataAquisicao");

                    b.Property<string>("MaquinaDetalhes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MaquinaDetalhes");

                    b.Property<string>("MaquinaFotoUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("FotoUrl");

                    b.Property<string>("MaquinaModelo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Modelo");

                    b.Property<string>("MaquinaNome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Nome");

                    b.Property<int>("MaquinaNumeroSerie")
                        .HasColumnType("int")
                        .HasColumnName("NumeroSerie");

                    b.Property<float>("MaquinaPeso")
                        .HasColumnType("real")
                        .HasColumnName("Peso");

                    b.Property<int>("MaquinaVoltagem")
                        .HasColumnType("int")
                        .HasColumnName("Voltagem");

                    b.Property<int>("SetorId")
                        .HasColumnType("int")
                        .HasColumnName("SetorId");

                    b.Property<int>("TipoMaquinaId")
                        .HasColumnType("int")
                        .HasColumnName("TipoMaquinaId");

                    b.HasKey("Id");

                    b.HasIndex("FabricanteId");

                    b.HasIndex("SetorId");

                    b.HasIndex("TipoMaquinaId");

                    b.ToTable("Maquina");
                });

            modelBuilder.Entity("SistemaGHMM.Models.PecaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PecaId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaPecaId")
                        .HasColumnType("int")
                        .HasColumnName("CategoriaPeca");

                    b.Property<int>("FornecedorId")
                        .HasColumnType("int")
                        .HasColumnName("Fornecedor");

                    b.Property<string>("PecaNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PecaNome");

                    b.Property<int>("QuantidadeEstoque")
                        .HasColumnType("int")
                        .HasColumnName("QuantidadeEstoque");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaPecaId");

                    b.HasIndex("FornecedorId");

                    b.ToTable("Peca");
                });

            modelBuilder.Entity("SistemaGHMM.Models.SetorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SetorId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SetorNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SetorNome");

                    b.HasKey("Id");

                    b.ToTable("Setor");
                });

            modelBuilder.Entity("SistemaGHMM.Models.TecnicoTipoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TecnicoTipoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TecnicoTipoDescricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TecnicoDescricao");

                    b.HasKey("Id");

                    b.ToTable("TecnicoTipo");
                });

            modelBuilder.Entity("SistemaGHMM.Models.TecnicoUsuarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TecnicoUsuarioId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("TecnicosId")
                        .HasColumnType("int")
                        .HasColumnName("Tecnicos");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("Usuario");

                    b.HasKey("Id");

                    b.HasIndex("TecnicosId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TecnicoUsuario");
                });

            modelBuilder.Entity("SistemaGHMM.Models.TecnicosModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TecnicosId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TecnicoDatalhes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TecnicoDetalhes");

                    b.Property<string>("TecnicoNome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TecnicoNome");

                    b.Property<int>("TecnicoTipoId")
                        .HasColumnType("int")
                        .HasColumnName("TecnicoTipo");

                    b.HasKey("Id");

                    b.HasIndex("TecnicoTipoId");

                    b.ToTable("Tecnicos");
                });

            modelBuilder.Entity("SistemaGHMM.Models.TipoManutencaoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TipoManutencaoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TipoManutencaoNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TipoManutencaoNome");

                    b.HasKey("Id");

                    b.ToTable("TipoManutencao");
                });

            modelBuilder.Entity("SistemaGHMM.Models.TipoMaquinaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TipoMaquinaId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TipoMaquinaNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TipoMaquinaNome");

                    b.HasKey("Id");

                    b.ToTable("TipoMaquina");
                });

            modelBuilder.Entity("SistemaGHMM.Models.UsuarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UsuarioId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CargoId")
                        .HasColumnType("int");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FotoUrl");

                    b.Property<int>("SetorId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioCpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UsuarioCpf");

                    b.Property<DateTime>("UsuarioDataNascimento")
                        .HasColumnType("datetime2")
                        .HasColumnName("UsuarioDataNascimento");

                    b.Property<string>("UsuarioEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UsuarioEmail");

                    b.Property<string>("UsuarioEscolaridade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UsuarioEscolaridade");

                    b.Property<string>("UsuarioNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UsuarioNome");

                    b.Property<string>("UsuarioSenha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UsuarioSenha");

                    b.Property<string>("UsuarioTelefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UsuarioTelefone");

                    b.HasKey("Id");

                    b.HasIndex("CargoId");

                    b.HasIndex("SetorId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("SistemaGHMM.Models.AvisoModel", b =>
                {
                    b.HasOne("SistemaGHMM.Models.AvisoTipoModel", "AvisoTipo")
                        .WithMany()
                        .HasForeignKey("AvisoTipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaGHMM.Models.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AvisoTipo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaGHMM.Models.ManutencaoEPecasModel", b =>
                {
                    b.HasOne("SistemaGHMM.Models.ManutencaoModel", "Manutencao")
                        .WithMany()
                        .HasForeignKey("ManutencaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaGHMM.Models.PecaModel", "Peca")
                        .WithMany()
                        .HasForeignKey("PecaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manutencao");

                    b.Navigation("Peca");
                });

            modelBuilder.Entity("SistemaGHMM.Models.ManutencaoModel", b =>
                {
                    b.HasOne("SistemaGHMM.Models.TecnicosModel", "Tecnicos")
                        .WithMany()
                        .HasForeignKey("TecnicosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaGHMM.Models.TipoManutencaoModel", "TipoManutencao")
                        .WithMany()
                        .HasForeignKey("TipoManutencaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tecnicos");

                    b.Navigation("TipoManutencao");
                });

            modelBuilder.Entity("SistemaGHMM.Models.MaquinaModel", b =>
                {
                    b.HasOne("SistemaGHMM.Models.FabricanteModel", "Fabricante")
                        .WithMany()
                        .HasForeignKey("FabricanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaGHMM.Models.SetorModel", "Setor")
                        .WithMany()
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaGHMM.Models.TipoMaquinaModel", "TipoMaquina")
                        .WithMany()
                        .HasForeignKey("TipoMaquinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fabricante");

                    b.Navigation("Setor");

                    b.Navigation("TipoMaquina");
                });

            modelBuilder.Entity("SistemaGHMM.Models.PecaModel", b =>
                {
                    b.HasOne("SistemaGHMM.Models.CategoriaPecaModel", "CategoriaPeca")
                        .WithMany()
                        .HasForeignKey("CategoriaPecaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaGHMM.Models.FornecedorModel", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaPeca");

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("SistemaGHMM.Models.TecnicoUsuarioModel", b =>
                {
                    b.HasOne("SistemaGHMM.Models.TecnicosModel", "Tecnicos")
                        .WithMany()
                        .HasForeignKey("TecnicosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaGHMM.Models.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tecnicos");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaGHMM.Models.TecnicosModel", b =>
                {
                    b.HasOne("SistemaGHMM.Models.TecnicoTipoModel", "TecnicoTipo")
                        .WithMany()
                        .HasForeignKey("TecnicoTipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TecnicoTipo");
                });

            modelBuilder.Entity("SistemaGHMM.Models.UsuarioModel", b =>
                {
                    b.HasOne("SistemaGHMM.Models.CargoModel", "Cargo")
                        .WithMany()
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaGHMM.Models.SetorModel", "Setor")
                        .WithMany()
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("Setor");
                });
#pragma warning restore 612, 618
        }
    }
}
